import type { JobInfo, JobId } from '@/types/character';

// ============================================================================
// Job Definitions
// ============================================================================

export const JOBS: Record<JobId, JobInfo> = {
  // Beginner
  beginner: {
    id: 'beginner',
    name: '초보자',
    branch: null,
    advancement: 0,
    requiredLevel: 1,
    primaryStat: 'str',
    previousJob: null,
  },

  // Warrior Branch
  warrior: {
    id: 'warrior',
    name: '전사',
    branch: 'warrior',
    advancement: 1,
    requiredLevel: 10,
    primaryStat: 'str',
    previousJob: 'beginner',
  },
  fighter: {
    id: 'fighter',
    name: '파이터',
    branch: 'warrior',
    advancement: 2,
    requiredLevel: 30,
    primaryStat: 'str',
    previousJob: 'warrior',
  },
  crusader: {
    id: 'crusader',
    name: '크루세이더',
    branch: 'warrior',
    advancement: 3,
    requiredLevel: 70,
    primaryStat: 'str',
    previousJob: 'fighter',
  },
  hero: {
    id: 'hero',
    name: '히어로',
    branch: 'warrior',
    advancement: 4,
    requiredLevel: 120,
    primaryStat: 'str',
    previousJob: 'crusader',
  },
  page: {
    id: 'page',
    name: '페이지',
    branch: 'warrior',
    advancement: 2,
    requiredLevel: 30,
    primaryStat: 'str',
    previousJob: 'warrior',
  },
  knight: {
    id: 'knight',
    name: '나이트',
    branch: 'warrior',
    advancement: 3,
    requiredLevel: 70,
    primaryStat: 'str',
    previousJob: 'page',
  },
  paladin: {
    id: 'paladin',
    name: '팔라딘',
    branch: 'warrior',
    advancement: 4,
    requiredLevel: 120,
    primaryStat: 'str',
    previousJob: 'knight',
  },
  spearman: {
    id: 'spearman',
    name: '스피어맨',
    branch: 'warrior',
    advancement: 2,
    requiredLevel: 30,
    primaryStat: 'str',
    previousJob: 'warrior',
  },
  dragon_knight: {
    id: 'dragon_knight',
    name: '드래곤나이트',
    branch: 'warrior',
    advancement: 3,
    requiredLevel: 70,
    primaryStat: 'str',
    previousJob: 'spearman',
  },
  dark_knight: {
    id: 'dark_knight',
    name: '다크나이트',
    branch: 'warrior',
    advancement: 4,
    requiredLevel: 120,
    primaryStat: 'str',
    previousJob: 'dragon_knight',
  },

  // Magician Branch
  magician: {
    id: 'magician',
    name: '마법사',
    branch: 'magician',
    advancement: 1,
    requiredLevel: 8,
    primaryStat: 'int',
    previousJob: 'beginner',
  },
  wizard_fp: {
    id: 'wizard_fp',
    name: '위자드(불/독)',
    branch: 'magician',
    advancement: 2,
    requiredLevel: 30,
    primaryStat: 'int',
    previousJob: 'magician',
  },
  mage_fp: {
    id: 'mage_fp',
    name: '메이지(불/독)',
    branch: 'magician',
    advancement: 3,
    requiredLevel: 70,
    primaryStat: 'int',
    previousJob: 'wizard_fp',
  },
  archmage_fp: {
    id: 'archmage_fp',
    name: '아크메이지(불/독)',
    branch: 'magician',
    advancement: 4,
    requiredLevel: 120,
    primaryStat: 'int',
    previousJob: 'mage_fp',
  },
  wizard_il: {
    id: 'wizard_il',
    name: '위자드(썬/콜)',
    branch: 'magician',
    advancement: 2,
    requiredLevel: 30,
    primaryStat: 'int',
    previousJob: 'magician',
  },
  mage_il: {
    id: 'mage_il',
    name: '메이지(썬/콜)',
    branch: 'magician',
    advancement: 3,
    requiredLevel: 70,
    primaryStat: 'int',
    previousJob: 'wizard_il',
  },
  archmage_il: {
    id: 'archmage_il',
    name: '아크메이지(썬/콜)',
    branch: 'magician',
    advancement: 4,
    requiredLevel: 120,
    primaryStat: 'int',
    previousJob: 'mage_il',
  },
  cleric: {
    id: 'cleric',
    name: '클레릭',
    branch: 'magician',
    advancement: 2,
    requiredLevel: 30,
    primaryStat: 'int',
    previousJob: 'magician',
  },
  priest: {
    id: 'priest',
    name: '프리스트',
    branch: 'magician',
    advancement: 3,
    requiredLevel: 70,
    primaryStat: 'int',
    previousJob: 'cleric',
  },
  bishop: {
    id: 'bishop',
    name: '비숍',
    branch: 'magician',
    advancement: 4,
    requiredLevel: 120,
    primaryStat: 'int',
    previousJob: 'priest',
  },

  // Archer Branch
  archer: {
    id: 'archer',
    name: '궁수',
    branch: 'archer',
    advancement: 1,
    requiredLevel: 10,
    primaryStat: 'dex',
    previousJob: 'beginner',
  },
  hunter: {
    id: 'hunter',
    name: '헌터',
    branch: 'archer',
    advancement: 2,
    requiredLevel: 30,
    primaryStat: 'dex',
    previousJob: 'archer',
  },
  ranger: {
    id: 'ranger',
    name: '레인저',
    branch: 'archer',
    advancement: 3,
    requiredLevel: 70,
    primaryStat: 'dex',
    previousJob: 'hunter',
  },
  bowmaster: {
    id: 'bowmaster',
    name: '보우마스터',
    branch: 'archer',
    advancement: 4,
    requiredLevel: 120,
    primaryStat: 'dex',
    previousJob: 'ranger',
  },
  crossbowman: {
    id: 'crossbowman',
    name: '사수',
    branch: 'archer',
    advancement: 2,
    requiredLevel: 30,
    primaryStat: 'dex',
    previousJob: 'archer',
  },
  sniper: {
    id: 'sniper',
    name: '저격수',
    branch: 'archer',
    advancement: 3,
    requiredLevel: 70,
    primaryStat: 'dex',
    previousJob: 'crossbowman',
  },
  marksman: {
    id: 'marksman',
    name: '신궁',
    branch: 'archer',
    advancement: 4,
    requiredLevel: 120,
    primaryStat: 'dex',
    previousJob: 'sniper',
  },

  // Thief Branch
  thief: {
    id: 'thief',
    name: '도적',
    branch: 'thief',
    advancement: 1,
    requiredLevel: 10,
    primaryStat: 'luk',
    previousJob: 'beginner',
  },
  assassin: {
    id: 'assassin',
    name: '어쌔신',
    branch: 'thief',
    advancement: 2,
    requiredLevel: 30,
    primaryStat: 'luk',
    previousJob: 'thief',
  },
  hermit: {
    id: 'hermit',
    name: '허밋',
    branch: 'thief',
    advancement: 3,
    requiredLevel: 70,
    primaryStat: 'luk',
    previousJob: 'assassin',
  },
  night_lord: {
    id: 'night_lord',
    name: '나이트로드',
    branch: 'thief',
    advancement: 4,
    requiredLevel: 120,
    primaryStat: 'luk',
    previousJob: 'hermit',
  },
  bandit: {
    id: 'bandit',
    name: '시프',
    branch: 'thief',
    advancement: 2,
    requiredLevel: 30,
    primaryStat: 'luk',
    previousJob: 'thief',
  },
  chief_bandit: {
    id: 'chief_bandit',
    name: '시프마스터',
    branch: 'thief',
    advancement: 3,
    requiredLevel: 70,
    primaryStat: 'luk',
    previousJob: 'bandit',
  },
  shadower: {
    id: 'shadower',
    name: '섀도어',
    branch: 'thief',
    advancement: 4,
    requiredLevel: 120,
    primaryStat: 'luk',
    previousJob: 'chief_bandit',
  },

  // Pirate Branch
  pirate: {
    id: 'pirate',
    name: '해적',
    branch: 'pirate',
    advancement: 1,
    requiredLevel: 10,
    primaryStat: 'str',
    previousJob: 'beginner',
  },
  infighter: {
    id: 'infighter',
    name: '인파이터',
    branch: 'pirate',
    advancement: 2,
    requiredLevel: 30,
    primaryStat: 'str',
    previousJob: 'pirate',
  },
  buccaneer: {
    id: 'buccaneer',
    name: '버커니어',
    branch: 'pirate',
    advancement: 3,
    requiredLevel: 70,
    primaryStat: 'str',
    previousJob: 'infighter',
  },
  viper: {
    id: 'viper',
    name: '바이퍼',
    branch: 'pirate',
    advancement: 4,
    requiredLevel: 120,
    primaryStat: 'str',
    previousJob: 'buccaneer',
  },
  gunslinger: {
    id: 'gunslinger',
    name: '건슬링거',
    branch: 'pirate',
    advancement: 2,
    requiredLevel: 30,
    primaryStat: 'dex',
    previousJob: 'pirate',
  },
  valkyrie: {
    id: 'valkyrie',
    name: '발키리',
    branch: 'pirate',
    advancement: 3,
    requiredLevel: 70,
    primaryStat: 'dex',
    previousJob: 'gunslinger',
  },
  captain: {
    id: 'captain',
    name: '캡틴',
    branch: 'pirate',
    advancement: 4,
    requiredLevel: 120,
    primaryStat: 'dex',
    previousJob: 'valkyrie',
  },
} as const;
